[package]
name = "defuse-erc191"
edition.workspace = true
version.workspace = true

[dependencies]
defuse-crypto = { workspace = true, features = ["serde"] }

impl-tools.workspace = true
near-sdk.workspace = true
serde_with.workspace = true

[features]
abi = []
