[package]
name = "defuse-num-utils"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
repository.workspace = true

[dependencies]
bnum.workspace = true

[lints]
workspace = true
