[package]
name = "defuse-wnear"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
repository.workspace = true

[dependencies]
near-contract-standards.workspace = true
near-sdk.workspace = true

[lints]
workspace = true
