[package]
name = "defuse-controller"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
repository.workspace = true

[dependencies]
near-sdk.workspace = true

[lints]
workspace = true
