[package]
name = "defuse-bitmap"
edition.workspace = true
version.workspace = true
repository.workspace = true

[dependencies]
defuse-map-utils.workspace = true

near-sdk = { workspace = true }

[dev-dependencies]
bnum.workspace = true
